// This follows construction 5 from the paper

use rand::{RngExt, SeedableRng, rngs::ChaCha20Rng};

/// Some large prime...
pub const Q: u32 = 13;

/// Some generator for integers modulo Q.
pub const G: u32 = 2;

/// Random seed. Change to take this as a command line argument later.
pub const SEED: u64 = 1;

#[derive(Debug)]
pub struct ElGamalPKE {
    q: u32,
    g: u32,
    rng: ChaCha20Rng,
}

impl Default for ElGamalPKE {
    /// Generates a default ElGamalPKE scheme using the hardcoded constants.
    /// Mostly for debugging... I imagine we'll remove this later.
    fn default() -> Self {
        Self {
            q: Q,
            g: G,
            rng: ChaCha20Rng::seed_from_u64(SEED),
        }
    }
}

impl ElGamalPKE {
    pub fn new(q: u32, g: u32) -> Self {
        Self {
            q,
            g,
            rng: ChaCha20Rng::seed_from_u64(SEED),
        }
    }

    /// Generates the `(pk, sk)` tuple.
    // gen is a reserved keyword in rust. We bypass this by using the r# syntax.
    //
    // Note that we need &mut self here instead of just &self because using self.rng requires
    // mutating self.rng.
    pub fn r#gen(&mut self) -> (u32, u32) {
        // sk = uniformly random integer < q
        let sk = self.rng.random_range(0..self.q);

        // pk = g^sk
        // We need to find a better way of handling modulo arithmetic that avoids overflow.
        // Maybe this crate? https://docs.rs/num-modular/0.6.1/num_modular/
        let pk = self.g.pow(sk) % self.q;

        // output (sk, pk)
        (sk, pk)
    }

    /// Checks whether a given integer is in the message space.
    /// The message space is defined as the integers in the cyclic group generated by powers of `g`, modulo `q`.
    // We need to find a better way to do this later.
    fn in_message_space(&self, m: u32) -> bool {
        if m == self.g {
            return true;
        }

        let mut i = self.g * self.g % self.q;
        while i != self.g {
            if m == i {
                return true;
            }

            i *= self.g;
            i %= self.q;
        }

        false
    }

    /// Uses the public key `pk` to encode message `m`.
    /// Note that `m` must be in the message space, which is the cyclic group generated by `g` modulo `q`.
    // This could well be wrong.
    pub fn enc(&mut self, pk: u32, m: u32) -> Option<(u32, u32)> {
        if !self.in_message_space(m) {
            return None;
        }

        // r = uniformly random integer < q
        let r = self.rng.random_range(0..self.q);

        // c1 = m * pk^r
        let c1 = (m * pk.pow(r)) % self.q;

        // c2 = g^r
        let c2 = self.g.pow(r) % self.q;

        // output (c1, c2)
        Some((c1, c2))
    }

    /// Uses the secret key `sk` to decode some ciphertext `(c1, c2)`.
    // Need to find some way to get the modulo multiplicative inverse
    #[allow(unused)]
    pub fn dec(&self, sk: u32, (c1, c2): (u32, u32)) -> u32 {
        // output c1 * c2^(-sk)

        todo!()
    }
}
