use std::marker::PhantomData;

use crypto_bigint::{Uint, modular::ConstMontyForm};
use rand::{RngExt, SeedableRng, rngs::ChaCha20Rng};

use crate::{
    groups::MultGroupParams,
    helpers::random_mod_lb,
    pke::{AnamorphicPKE, PKE},
};

/// The group of integers generated by some g mod p.
/// Has size q.
#[derive(Debug, Clone, Copy)]
pub struct MultGroupValue<const LIMBS: usize, G: MultGroupParams<LIMBS>>(
    ConstMontyForm<G::MOD, LIMBS>,
);

impl<const LIMBS: usize, G: MultGroupParams<LIMBS>> std::ops::Deref for MultGroupValue<LIMBS, G> {
    type Target = ConstMontyForm<G::MOD, LIMBS>;

    fn deref(&self) -> &Self::Target {
        let MultGroupValue(inner) = self;
        inner
    }
}

/// ElGamal encryption is defined over some group G
#[derive(Debug)]
pub struct ElGamal<const LIMBS: usize, G: MultGroupParams<LIMBS>> {
    rng: ChaCha20Rng,
    params: PhantomData<G>,
}

impl<const LIMBS: usize, G: MultGroupParams<LIMBS>> ElGamal<LIMBS, G> {
    pub fn new() -> Self {
        Self::new_seeded(rand::rng().random())
    }

    pub fn new_seeded(seed: u64) -> Self {
        Self {
            rng: ChaCha20Rng::seed_from_u64(seed),
            params: PhantomData,
        }
    }

    /// Takes some integer modulo p and checks that it is in the group generated by g (which has order q).
    /// If it is, yields an instance of the group type.
    fn into_group(&self, n: ConstMontyForm<G::MOD, LIMBS>) -> Option<MultGroupValue<LIMBS, G>> {
        if n.pow(&G::q()) != ConstMontyForm::ONE {
            // Message not in subgroup generated by g
            return None;
        }

        Some(MultGroupValue(n))
    }
}

impl<const LIMBS: usize, G: MultGroupParams<LIMBS>> PKE for ElGamal<LIMBS, G> {
    type PK = MultGroupValue<LIMBS, G>;

    type SK = Uint<LIMBS>;

    type M = MultGroupValue<LIMBS, G>;

    type C = (MultGroupValue<LIMBS, G>, MultGroupValue<LIMBS, G>);

    fn r#gen(&mut self) -> (Self::PK, Self::SK) {
        // sk = 0 is bad, because then c1 = m
        let sk = random_mod_lb(&mut self.rng, Uint::ONE, G::q());
        // This won't panic, since g^q is by definition in the group
        let pk = self.into_group(G::g().pow(&sk)).unwrap();

        (pk, sk)
    }

    fn enc(&mut self, m: Self::M, pk: Self::PK) -> Self::C {
        // Once again, we don't want r = 0, because then we have c1 = m
        let r = random_mod_lb(&mut self.rng, Uint::ONE, G::q());

        // This won't panic, since g^k * (g^a)^r = g^(k + a * r), which is in the group
        let c1 = self.into_group(*m * pk.pow(&r)).unwrap();
        // This won't panic, since this is the definition of being in the group
        let c2 = self.into_group(G::g().pow(&r)).unwrap();

        (c1, c2)
    }

    fn dec(&mut self, (c1, c2): Self::C, sk: Self::SK) -> Self::M {
        self.into_group(*c1 * c2.pow(&sk).invert().unwrap())
            .unwrap()
    }
}

impl<const LIMBS: usize, G: MultGroupParams<LIMBS>> AnamorphicPKE for ElGamal<LIMBS, G> {}
