// This follows construction 5 from the paper

use crypto_bigint::{
    NonZero, RandomMod, U4096, const_prime_monty_params,
    modular::{ConstMontyForm, ConstMontyParams},
};
use rand::{SeedableRng, rngs::ChaCha20Rng};

/// Random seed. Change to take this as a command line argument later.
pub const SEED: u64 = 1;

const P_STR: &str = "FFFFFFFFFFFFFFFFADF85458A2BB4A9AAFDC5620273D3CF1D8B9C583CE2D3695A9E13641146433FBCC939DCE249B3EF97D2FE363630C75D8F681B202AEC4617AD3DF1ED5D5FD65612433F51F5F066ED0856365553DED1AF3B557135E7F57C935984F0C70E0E68B77E2A689DAF3EFE8721DF158A136ADE73530ACCA4F483A797ABC0AB182B324FB61D108A94BB2C8E3FBB96ADAB760D7F4681D4F42A3DE394DF4AE56EDE76372BB190B07A7C8EE0A6D709E02FCE1CDF7E2ECC03404CD28342F619172FE9CE98583FF8E4F1232EEF28183C3FE3B1B4C6FAD733BB5FCBC2EC22005C58EF1837D1683B2C6F34A26C1B2EFFA886B4238611FCFDCDE355B3B6519035BBC34F4DEF99C023861B46FC9D6E6C9077AD91D2691F7F7EE598CB0FAC186D91CAEFE130985139270B4130C93BC437944F4FD4452E2D74DD364F2E21E71F54BFF5CAE82AB9C9DF69EE86D2BC522363A0DABC521979B0DEADA1DBF9A42D5C4484E0ABCD06BFA53DDEF3C1B20EE3FD59D7C25E41D2B669E1EF16E6F52C3164DF4FB7930E9E4E58857B6AC7D5F42D69F6D187763CF1D5503400487F55BA57E31CC7A7135C886EFB4318AED6A1E012D9E6832A907600A918130C46DC778F971AD0038092999A333CB8B7A1A1DB93D7140003C2A4ECEA9F98D0ACC0A8291CDCEC97DCF8EC9B55A7F88A46B4DB5A851F44182E1C68A007E5E655F6AFFFFFFFFFFFFFFFF";

/// Very large prime (RFC 7919, A.3).
pub const P: U4096 = U4096::from_be_hex(P_STR);

const_prime_monty_params!(ModP, U4096, P_STR, 2);

pub type P4096 = ConstMontyForm<ModP, { U4096::LIMBS }>;

/// Generator for a subgroup of size Q (of integers modulo P).
pub const G: P4096 = P4096::new(&U4096::from_u8(2));

/// Q = (p - 1) / 2.
///
/// Order of subgroup generated by G (modulo P).
/// Also a very large prime.
pub const Q: NonZero<U4096> = NonZero::<U4096>::new_unwrap(U4096::from_be_hex(
    "7FFFFFFFFFFFFFFFD6FC2A2C515DA54D57EE2B10139E9E78EC5CE2C1E7169B4AD4F09B208A3219FDE649CEE7124D9F7CBE97F1B1B1863AEC7B40D901576230BD69EF8F6AEAFEB2B09219FA8FAF83376842B1B2AA9EF68D79DAAB89AF3FABE49ACC278638707345BBF15344ED79F7F4390EF8AC509B56F39A98566527A41D3CBD5E0558C159927DB0E88454A5D96471FDDCB56D5BB06BFA340EA7A151EF1CA6FA572B76F3B1B95D8C8583D3E4770536B84F017E70E6FBF176601A0266941A17B0C8B97F4E74C2C1FFC7278919777940C1E1FF1D8DA637D6B99DDAFE5E17611002E2C778C1BE8B41D96379A51360D977FD4435A11C308FE7EE6F1AAD9DB28C81ADDE1A7A6F7CCE011C30DA37E4EB736483BD6C8E9348FBFBF72CC6587D60C36C8E577F0984C289C9385A098649DE21BCA27A7EA229716BA6E9B279710F38FAA5FFAE574155CE4EFB4F743695E2911B1D06D5E290CBCD86F56D0EDFCD216AE22427055E6835FD29EEF79E0D90771FEACEBE12F20E95B34F0F78B737A9618B26FA7DBC9874F272C42BDB563EAFA16B4FB68C3BB1E78EAA81A00243FAADD2BF18E63D389AE44377DA18C576B50F0096CF34195483B00548C0986236E3BC7CB8D6801C0494CCD199E5C5BD0D0EDC9EB8A0001E15276754FCC68566054148E6E764BEE7C764DAAD3FC45235A6DAD428FA20C170E345003F2F32AFB57FFFFFFFFFFFFFFF",
));

// #[derive(Debug)]
pub struct ElGamalPKE {
    rng: ChaCha20Rng,
}

impl ElGamalPKE {
    pub fn new() -> Self {
        Self {
            rng: ChaCha20Rng::seed_from_u64(SEED),
        }
    }

    /// Generates the `(pk, sk)` tuple.
    // gen is a reserved keyword in rust. We bypass this by using the r# syntax.
    //
    // Note that we need &mut self here instead of just &self because using self.rng requires
    // mutating self.rng.
    pub fn r#gen(&mut self) -> (U4096, U4096) {
        // sk = uniformly random integer < q
        let sk = U4096::random_mod_vartime(&mut self.rng, &Q);

        // pk = g^sk
        // We need to find a better way of handling modulo arithmetic that avoids overflow.
        // Maybe this crate? https://docs.rs/num-modular/0.6.1/num_modular/
        let pk = G.pow(&sk);

        // output (sk, pk)
        (sk, pk.retrieve())
    }

    /// Uses the public key `pk` to encode message `m`.
    /// Note that `m` must be in the message space, which is the cyclic group generated by `g` modulo `q`.
    // This could well be wrong.
    pub fn enc(&mut self, pk: U4096, m: U4096) -> Option<(U4096, U4096)> {
        if m == U4096::ZERO || &m >= ModP::PARAMS.modulus().as_ref() {
            // Message outside of message space.
            return None;
        }

        let m = P4096::new(&m);
        if m.pow(&Q) != P4096::ONE {
            // Message not in subgroup generated by g
            return None;
        }

        let pk = P4096::new(&pk);

        let r = U4096::random_mod_vartime(&mut self.rng, &Q);
        let c1 = m * pk.pow(&r);

        let c2 = G.pow(&r);

        Some((c1.retrieve(), c2.retrieve()))
    }

    /// Uses the secret key `sk` to decode some ciphertext `(c1, c2)`.
    // Need to find some way to get the modulo multiplicative inverse
    #[allow(unused)]
    pub fn dec(&self, sk: U4096, (c1, c2): (U4096, U4096)) -> U4096 {
        // output c1 * c2^(-sk)
        let c1 = P4096::new(&c1);
        let c2 = P4096::new(&c2);
        (c1 * c2.pow(&sk).invert().expect("Failed to invert")).retrieve()
    }
}

#[cfg(test)]
mod test {
    use crypto_bigint::U4096;

    use crate::el_gamal_pke::ElGamalPKE;

    #[test]
    fn verify_q() {
        assert_eq!(*super::Q, (super::P - U4096::ONE) / U4096::from_u8(2));
    }

    #[test]
    fn enc_dec_valid_1() {
        let mut pke = ElGamalPKE::new();
        let (sk, pk) = pke.r#gen();

        let m = U4096::from_u8(5);
        let (c1, c2) = pke.enc(pk, m).expect("m should be in subgroup");

        let m_dec = pke.dec(sk, (c1, c2));
        assert_eq!(m, m_dec);
    }
}
