use std::ops::Deref;

use crypto_bigint::{
    NonZero, Uint, const_monty_params,
    modular::{ConstMontyForm, ConstMontyParams},
};

/// A multiplicative cyclic group is defined modulo p (as defined in the MOD type).
/// The generator g generates a cyclic group of prime order q.
///
/// There are no checks in place for this (because actually computing it would be infeasible),
/// but for security these groups should only be defined for prime p and q
/// (i.e. q is a Sophie-Germain prime, and p is a safe prime).
pub trait MCG<const LIMBS: usize>: Deref<Target = ConstMontyForm<Self::MOD, LIMBS>> {
    type MOD: ConstMontyParams<LIMBS>;

    fn q() -> NonZero<Uint<LIMBS>>
    where
        Self: Sized;
    fn g() -> ConstMontyForm<Self::MOD, LIMBS>
    where
        Self: Sized;

    fn p() -> Uint<LIMBS>
    where
        Self: Sized,
    {
        **Self::MOD::PARAMS.modulus()
    }

    fn into_inner(self) -> ConstMontyForm<Self::MOD, LIMBS>;

    fn contains(n: ConstMontyForm<Self::MOD, LIMBS>) -> bool;

    /// Takes some integer modulo p and checks that it is in the group generated by g (which has order q).
    /// If it is, yields an instance of the group type.
    fn from_modp(n: ConstMontyForm<Self::MOD, LIMBS>) -> Option<Self>
    where
        Self: Sized;

    /// Converts some integer in \[0, q) to it's corresponding integer that is a member of G.
    /// This allows us to map Z_q (kind of) to G, which makes encoding messages a lot easier,
    /// since now the message space can be treated as Z_q instead of G (which has lots of gaps).
    ///
    /// This works by exploiting the fact that since p = 2 * q + 1 and both p and q are prime,
    /// the quadratic residue modulo p are exactly the members of G.
    /// We therefore map integers that are quadratic residue modulo p to themselves,
    /// and integers that are not to their negation (which is guaranteed to be both > q and in G).
    ///
    /// Returns None if n is not an integer modq.
    fn from_modq(n: Uint<LIMBS>) -> Option<Self>
    where
        Self: Sized;

    /// Reverse operation of [from_modq]
    fn to_modq(&self) -> Uint<LIMBS>
    where
        Self: Sized;
}

#[macro_export]
macro_rules! new_group {
    ($name:ident, $mod_name:ident, $limbs:expr, $p:expr, $q:expr, $g:expr $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub struct $name(ConstMontyForm<$mod_name, $limbs>);

        const_monty_params!($mod_name, Uint<$limbs>, $p);

        impl MCG<$limbs> for $name {
            type MOD = $mod_name;

            fn q() -> NonZero<Uint<$limbs>> {
                NonZero::from_be_hex($q)
            }

            fn g() -> ConstMontyForm<Self::MOD, $limbs> {
                ConstMontyForm::new(&Uint::from_u64($g))
            }

            fn into_inner(self) -> ConstMontyForm<Self::MOD, $limbs> {
                let Self(inner) = self;
                inner
            }

            fn contains(n: ConstMontyForm<Self::MOD, $limbs>) -> bool {
                n.pow(&Self::q()) == ConstMontyForm::ONE
            }

            fn from_modp(n: ConstMontyForm<Self::MOD, $limbs>) -> Option<Self> {
                if Self::contains(n) {
                    Some(Self(n))
                } else {
                    None
                }
            }

            fn from_modq(mut n: Uint<$limbs>) -> Option<Self> {
                if n >= *Self::q() {
                    return None;
                }

                // Technically encoding 0 using this process doesn't work,
                // so we just map 0 -> q.
                if n == Uint::ZERO {
                    n = *Self::q();
                }

                let n = ConstMontyForm::new(&n);

                if Self::contains(n) {
                    // If we're already in G, no need to map
                    Some(Self(n))
                } else {
                    let neg = n.neg();
                    debug_assert!(
                        Self::contains(neg),
                        "Something has gone wrong. Failed to lift {} into group.",
                        n.retrieve()
                    );

                    Some(Self(neg))
                }
            }

            fn to_modq(&self) -> Uint<$limbs> {
                let inner = self.into_inner();
                if inner.retrieve() == *Self::q() {
                    return Uint::ZERO;
                } else if inner.retrieve() < *Self::q() {
                    inner.retrieve()
                } else {
                    inner.neg().retrieve()
                }
            }
        }

        impl std::ops::Deref for $name {
            type Target = ConstMontyForm<$mod_name, $limbs>;

            fn deref(&self) -> &Self::Target {
                let $name(inner) = self;
                inner
            }
        }
    };
}

new_group!(
    GroupTiny,
    ModPTiny,
    1,
    "0000000000000017",
    "000000000000000B",
    2
);

new_group!(
    GroupSmall,
    ModPSmall,
    1,
    "00000000000000A7", // 167
    "0000000000000053", // 83
    2
);

new_group!(
    Group2048,
    ModP2048,
    32,
    "FFFFFFFFFFFFFFFFADF85458A2BB4A9AAFDC5620273D3CF1D8B9C583CE2D3695A9E13641146433FBCC939DCE249B3EF97D2FE363630C75D8F681B202AEC4617AD3DF1ED5D5FD65612433F51F5F066ED0856365553DED1AF3B557135E7F57C935984F0C70E0E68B77E2A689DAF3EFE8721DF158A136ADE73530ACCA4F483A797ABC0AB182B324FB61D108A94BB2C8E3FBB96ADAB760D7F4681D4F42A3DE394DF4AE56EDE76372BB190B07A7C8EE0A6D709E02FCE1CDF7E2ECC03404CD28342F619172FE9CE98583FF8E4F1232EEF28183C3FE3B1B4C6FAD733BB5FCBC2EC22005C58EF1837D1683B2C6F34A26C1B2EFFA886B423861285C97FFFFFFFFFFFFFFFF",
    "7FFFFFFFFFFFFFFFD6FC2A2C515DA54D57EE2B10139E9E78EC5CE2C1E7169B4AD4F09B208A3219FDE649CEE7124D9F7CBE97F1B1B1863AEC7B40D901576230BD69EF8F6AEAFEB2B09219FA8FAF83376842B1B2AA9EF68D79DAAB89AF3FABE49ACC278638707345BBF15344ED79F7F4390EF8AC509B56F39A98566527A41D3CBD5E0558C159927DB0E88454A5D96471FDDCB56D5BB06BFA340EA7A151EF1CA6FA572B76F3B1B95D8C8583D3E4770536B84F017E70E6FBF176601A0266941A17B0C8B97F4E74C2C1FFC7278919777940C1E1FF1D8DA637D6B99DDAFE5E17611002E2C778C1BE8B41D96379A51360D977FD4435A11C30942E4BFFFFFFFFFFFFFFFF",
    2
);

new_group!(
    Group3072,
    ModP3072,
    48,
    "FFFFFFFFFFFFFFFFADF85458A2BB4A9AAFDC5620273D3CF1D8B9C583CE2D3695A9E13641146433FBCC939DCE249B3EF97D2FE363630C75D8F681B202AEC4617AD3DF1ED5D5FD65612433F51F5F066ED0856365553DED1AF3B557135E7F57C935984F0C70E0E68B77E2A689DAF3EFE8721DF158A136ADE73530ACCA4F483A797ABC0AB182B324FB61D108A94BB2C8E3FBB96ADAB760D7F4681D4F42A3DE394DF4AE56EDE76372BB190B07A7C8EE0A6D709E02FCE1CDF7E2ECC03404CD28342F619172FE9CE98583FF8E4F1232EEF28183C3FE3B1B4C6FAD733BB5FCBC2EC22005C58EF1837D1683B2C6F34A26C1B2EFFA886B4238611FCFDCDE355B3B6519035BBC34F4DEF99C023861B46FC9D6E6C9077AD91D2691F7F7EE598CB0FAC186D91CAEFE130985139270B4130C93BC437944F4FD4452E2D74DD364F2E21E71F54BFF5CAE82AB9C9DF69EE86D2BC522363A0DABC521979B0DEADA1DBF9A42D5C4484E0ABCD06BFA53DDEF3C1B20EE3FD59D7C25E41D2B66C62E37FFFFFFFFFFFFFFFF",
    "7FFFFFFFFFFFFFFFD6FC2A2C515DA54D57EE2B10139E9E78EC5CE2C1E7169B4AD4F09B208A3219FDE649CEE7124D9F7CBE97F1B1B1863AEC7B40D901576230BD69EF8F6AEAFEB2B09219FA8FAF83376842B1B2AA9EF68D79DAAB89AF3FABE49ACC278638707345BBF15344ED79F7F4390EF8AC509B56F39A98566527A41D3CBD5E0558C159927DB0E88454A5D96471FDDCB56D5BB06BFA340EA7A151EF1CA6FA572B76F3B1B95D8C8583D3E4770536B84F017E70E6FBF176601A0266941A17B0C8B97F4E74C2C1FFC7278919777940C1E1FF1D8DA637D6B99DDAFE5E17611002E2C778C1BE8B41D96379A51360D977FD4435A11C308FE7EE6F1AAD9DB28C81ADDE1A7A6F7CCE011C30DA37E4EB736483BD6C8E9348FBFBF72CC6587D60C36C8E577F0984C289C9385A098649DE21BCA27A7EA229716BA6E9B279710F38FAA5FFAE574155CE4EFB4F743695E2911B1D06D5E290CBCD86F56D0EDFCD216AE22427055E6835FD29EEF79E0D90771FEACEBE12F20E95B363171BFFFFFFFFFFFFFFFF",
    2
);

new_group!(
    Group4096,
    ModP4096,
    64,
    "FFFFFFFFFFFFFFFFADF85458A2BB4A9AAFDC5620273D3CF1D8B9C583CE2D3695A9E13641146433FBCC939DCE249B3EF97D2FE363630C75D8F681B202AEC4617AD3DF1ED5D5FD65612433F51F5F066ED0856365553DED1AF3B557135E7F57C935984F0C70E0E68B77E2A689DAF3EFE8721DF158A136ADE73530ACCA4F483A797ABC0AB182B324FB61D108A94BB2C8E3FBB96ADAB760D7F4681D4F42A3DE394DF4AE56EDE76372BB190B07A7C8EE0A6D709E02FCE1CDF7E2ECC03404CD28342F619172FE9CE98583FF8E4F1232EEF28183C3FE3B1B4C6FAD733BB5FCBC2EC22005C58EF1837D1683B2C6F34A26C1B2EFFA886B4238611FCFDCDE355B3B6519035BBC34F4DEF99C023861B46FC9D6E6C9077AD91D2691F7F7EE598CB0FAC186D91CAEFE130985139270B4130C93BC437944F4FD4452E2D74DD364F2E21E71F54BFF5CAE82AB9C9DF69EE86D2BC522363A0DABC521979B0DEADA1DBF9A42D5C4484E0ABCD06BFA53DDEF3C1B20EE3FD59D7C25E41D2B669E1EF16E6F52C3164DF4FB7930E9E4E58857B6AC7D5F42D69F6D187763CF1D5503400487F55BA57E31CC7A7135C886EFB4318AED6A1E012D9E6832A907600A918130C46DC778F971AD0038092999A333CB8B7A1A1DB93D7140003C2A4ECEA9F98D0ACC0A8291CDCEC97DCF8EC9B55A7F88A46B4DB5A851F44182E1C68A007E5E655F6AFFFFFFFFFFFFFFFF",
    "7FFFFFFFFFFFFFFFD6FC2A2C515DA54D57EE2B10139E9E78EC5CE2C1E7169B4AD4F09B208A3219FDE649CEE7124D9F7CBE97F1B1B1863AEC7B40D901576230BD69EF8F6AEAFEB2B09219FA8FAF83376842B1B2AA9EF68D79DAAB89AF3FABE49ACC278638707345BBF15344ED79F7F4390EF8AC509B56F39A98566527A41D3CBD5E0558C159927DB0E88454A5D96471FDDCB56D5BB06BFA340EA7A151EF1CA6FA572B76F3B1B95D8C8583D3E4770536B84F017E70E6FBF176601A0266941A17B0C8B97F4E74C2C1FFC7278919777940C1E1FF1D8DA637D6B99DDAFE5E17611002E2C778C1BE8B41D96379A51360D977FD4435A11C308FE7EE6F1AAD9DB28C81ADDE1A7A6F7CCE011C30DA37E4EB736483BD6C8E9348FBFBF72CC6587D60C36C8E577F0984C289C9385A098649DE21BCA27A7EA229716BA6E9B279710F38FAA5FFAE574155CE4EFB4F743695E2911B1D06D5E290CBCD86F56D0EDFCD216AE22427055E6835FD29EEF79E0D90771FEACEBE12F20E95B34F0F78B737A9618B26FA7DBC9874F272C42BDB563EAFA16B4FB68C3BB1E78EAA81A00243FAADD2BF18E63D389AE44377DA18C576B50F0096CF34195483B00548C0986236E3BC7CB8D6801C0494CCD199E5C5BD0D0EDC9EB8A0001E15276754FCC68566054148E6E764BEE7C764DAAD3FC45235A6DAD428FA20C170E345003F2F32AFB57FFFFFFFFFFFFFFF",
    2
);

#[cfg(test)]
mod tests {
    use crypto_bigint::U64;

    use crate::groups::{GroupSmall, GroupTiny, MCG};

    #[test]
    fn test_into_group_tiny() {
        let mut results = vec![];

        let mut i = U64::ZERO;
        while i < *GroupTiny::q() {
            let g = GroupTiny::from_modq(i).unwrap();
            assert!(!results.contains(&g));
            results.push(g);
            i += U64::ONE;
        }
    }

    #[test]
    fn test_into_group_small() {
        let mut results = vec![];

        let mut i = U64::ZERO;
        while i < *GroupSmall::q() {
            let g = GroupSmall::from_modq(i).unwrap();
            assert!(!results.contains(&g), "{} already seen!", g.retrieve());
            results.push(g);
            i += U64::ONE;
        }
    }
}
