use clap::{Parser, Subcommand, ValueEnum};
use crypto_bigint::Uint;

use crate::el_gamal_pke::ElGamalPKE;

mod el_gamal_pke;

// Just setting this up for normal PKE encrpytion rn.
// We'll need to rethink the CLI later once we add anamorphic too.
#[derive(Parser, Debug, Clone)]
struct Args {
    size: Size,

    #[command(subcommand)]
    mode: Mode,
}

#[derive(ValueEnum, Debug, Clone)]
enum Size {
    /// Message space = {1, 2, 3, 4, 6, 8, 9, 12, 13, 16, 18}
    Tiny,
    /// 2048-bit primes
    Small,
    /// 3072-bit primes
    Medium,
    /// 4096-bit primes
    Large,
}

#[derive(Subcommand, Debug, Clone)]
enum Mode {
    /// Normal ElGamal PKE
    #[command(subcommand, aliases = ["n", "norm"])]
    Normal(NormalOp),

    /// Anamorphic ElGamal PKE
    #[command(subcommand, aliases = ["a", "anamorphic"])]
    Anam(AnamOp),
}

#[derive(Subcommand, Debug, Clone)]
enum NormalOp {
    /// Generate public / secret key pair.
    Gen {},
    /// Encode some message using a public key.
    Enc {
        /// Public key generated by running the `gen` command.
        pk: String,

        /// Hex coding of message. Note that not all messages are representable.
        m: String,
    },
    /// Decode a ciphertext pair using a secret key.
    Dec {
        /// Secret key generated by running the `gen` command.
        sk: String,

        /// Ciphertext 1
        c1: String,

        /// Ciphertext 2
        c2: String,
    },
}

#[derive(Subcommand, Debug, Clone)]
enum AnamOp {
    /// Generate public / secret / double key triplet.
    Gen {},
    // TODO: The rest of these
}

fn run<const LIMBS: usize, MOD: crypto_bigint::modular::ConstMontyParams<LIMBS>>(
    pke: &mut ElGamalPKE<LIMBS, MOD>,
    mode: &Mode,
) -> Result<(), Box<dyn std::error::Error>> {
    match mode {
        Mode::Normal(op) => run_normal(pke, op),
        Mode::Anam(op) => run_anam(pke, op),
    }
}

fn run_normal<const LIMBS: usize, MOD: crypto_bigint::modular::ConstMontyParams<LIMBS>>(
    pke: &mut ElGamalPKE<LIMBS, MOD>,
    op: &NormalOp,
) -> Result<(), Box<dyn std::error::Error>> {
    match op {
        NormalOp::Gen {} => {
            let (sk, pk) = pke.r#gen();
            println!("pk: {}", pk);
            println!("sk: {}", sk);
        }
        NormalOp::Enc { pk, m } => {
            // TODO: Parse these without panicking
            let pk = Uint::<LIMBS>::from_be_hex(pk.as_str());

            if let Some((c1, c2)) = pke.enc_str(pk, m) {
                println!("c1: {}", c1);
                println!("c2: {}", c2);
            } else {
                eprintln!("The message is not in the message space.");
            }
        }
        NormalOp::Dec { sk, c1, c2 } => {
            let sk = Uint::<LIMBS>::from_be_hex(sk.as_str());
            let c1 = Uint::<LIMBS>::from_be_hex(c1.as_str());
            let c2 = Uint::<LIMBS>::from_be_hex(c2.as_str());

            let m = pke
                .dec_str(sk, (c1, c2))
                .ok_or("failed to decode to string")?;
            println!("m: {}", m);
        }
    }

    Ok(())
}

fn run_anam<const LIMBS: usize, MOD: crypto_bigint::modular::ConstMontyParams<LIMBS>>(
    pke: &mut ElGamalPKE<LIMBS, MOD>,
    op: &AnamOp,
) -> Result<(), Box<dyn std::error::Error>> {
    match op {
        AnamOp::Gen {} => todo!(),
    }

    Ok(())
}

// This return type just means that we propagate errors from any result type up
// to main by using the ? operator.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();

    match args.size {
        Size::Tiny => run(
            &mut match args.mode {
                Mode::Normal(_) => ElGamalPKE::new_tiny(),
                Mode::Anam(_) => ElGamalPKE::new_tiny_with_ame(4, 1, 1), // TODO: How do we choose these?
            },
            &args.mode,
        ),
        Size::Small => run(
            &mut match args.mode {
                Mode::Normal(_) => ElGamalPKE::new_2048(),
                Mode::Anam(_) => ElGamalPKE::new_2048_with_ame(16, 64, 64), // TODO: How do we choose these?
            },
            &args.mode,
        ),
        Size::Medium => run(
            &mut match args.mode {
                Mode::Normal(_) => ElGamalPKE::new_3072(),
                Mode::Anam(_) => ElGamalPKE::new_3072_with_ame(16, 64, 64), // TODO: How do we choose these?
            },
            &args.mode,
        ),
        Size::Large => run(
            &mut match args.mode {
                Mode::Normal(_) => ElGamalPKE::new_4096(),
                Mode::Anam(_) => ElGamalPKE::new_4096_with_ame(16, 64, 64), // TODO: How do we choose these?
            },
            &args.mode,
        ),
    }
}
