use clap::{Parser, Subcommand, ValueEnum};
use crypto_bigint::Uint;

use crate::el_gamal_pke::ElGamalPKE;

mod el_gamal_pke;

// Just setting this up for normal PKE encrpytion rn.
// We'll need to rethink the CLI later once we add anamorphic too.
#[derive(Parser, Debug, Clone)]
struct Args {
    size: Size,

    #[command(subcommand)]
    mode: Mode,
}

#[derive(ValueEnum, Debug, Clone)]
enum Size {
    /// Message space = {1, 2, 3, 4, 6, 8, 9, 12, 13, 16, 18}
    Tiny,
    /// 2048-bit primes
    Small,
    /// 3072-bit primes
    Medium,
    /// 4096-bit primes
    Large,
}

#[derive(Subcommand, Debug, Clone)]
enum Mode {
    /// Generate public / secret key pair.
    Gen {},
    /// Encode some message using a public key.
    Enc {
        /// Public key generated by running the `gen` command.
        pk: String,

        /// Hex coding of message. Note that not all messages are representable.
        m: String,
    },
    /// Decode a ciphertext pair using a secret key.
    Dec {
        /// Secret key generated by running the `gen` command.
        sk: String,

        /// Ciphertext 1
        c1: String,

        /// Ciphertext 2
        c2: String,
    },
}

fn run<const LIMBS: usize, MOD: crypto_bigint::modular::ConstMontyParams<LIMBS>>(
    mut pke: ElGamalPKE<LIMBS, MOD>,
    mode: &Mode,
) -> Result<(), Box<dyn std::error::Error>> {
    match mode {
        Mode::Gen {} => {
            let (sk, pk) = pke.r#gen();
            println!("pk: {}", pk);
            println!("sk: {}", sk);
        }
        Mode::Enc { pk, m } => {
            // TODO: Parse these without panicking
            let pk = Uint::<LIMBS>::from_be_hex(pk.as_str());
            println!("{}", m);

            if let Some((c1, c2)) = pke.enc_str(pk, m) {
                println!("c1: {}", c1);
                println!("c2: {}", c2);
            } else {
                eprintln!("The message is not in the message space.");
            }
        }
        Mode::Dec { sk, c1, c2 } => {
            let sk = Uint::<LIMBS>::from_be_hex(sk.as_str());
            let c1 = Uint::<LIMBS>::from_be_hex(c1.as_str());
            let c2 = Uint::<LIMBS>::from_be_hex(c2.as_str());

            let m = pke
                .dec_str(sk, (c1, c2))
                .ok_or("failed to decode to string")?;
            println!("m: {}", m);
        }
    }

    Ok(())
}

// This return type just means that we propagate errors from any result type up
// to main by using the ? operator.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();

    match args.size {
        Size::Tiny => run(ElGamalPKE::new_tiny(), &args.mode),
        Size::Small => run(ElGamalPKE::new_2048(), &args.mode),
        Size::Medium => run(ElGamalPKE::new_3072(), &args.mode),
        Size::Large => run(ElGamalPKE::new_4096(), &args.mode),
    }
}
